# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RfimsLoader
                                 A QGIS plugin
 Loads RS & BS kml files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-10
        copyright            : (C) 2018 by Patrick Early/LGS Innovations
        email                : pearly@lgsinnovations.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RfimsLoader class from file RfimsLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rfims_loader import RfimsLoader
    return RfimsLoader(iface)
